### ISSUE TITLE
ActiveRecord support

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [codebrawl/arnold#1]
Let's support Mongoid and ActiveRecord for now. Adding it and running the specs on it should be easy, the specs are written to support multiple backends, but only Mongoid has been implemented right now.

Also, let's find a way so we don't have to have a database connection for running the tests. :)

Does anyone want to pick this one up? :)

**Comment by razielgn** [comment]
I'll probably try something tomorrow.

**Comment by jeffkreeftmeijer** [comment]
Awesome. Assigned it to you. Don't worry, you can always un-assign. :)
