### ISSUE TITLE
Don't show all fields in the editor

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [codebrawl/arnold#2]
Right now, the editor shows a YAML-ized version of _all_ attributes, but we probably don't want the id in there. I think it'd be good not to show the id (and maybe some others) by default, but allow the user to add a flag if they want to see those fields anyway.

Any thoughts? :)

**Comment by levicole** [comment]
I will pick this up. I handled this in my implementation for the contest.

Also, it might be cool to be able to specify which attributes you want to edit. Say if you are editing a blog post, and you just want to edit the body, you can pass in a symbol for editing just the body. in code:

``` ruby
@blog = Blog.find(1)
@blog.edit(:body)
```

**Comment by razielgn** [comment]
I think we should prepend something to the edit method, in order to avoid a possible collision with a pre-existing attribute.

**Comment by jeffkreeftmeijer** [comment]
@levicole +1. It would be cool to allow the user to specify an array of fields too! :)

@razielgn do ActiveRecord and Mongoid define `edit`? I thought not (I could be wrong, though). Also, maybe it's better to discuss this in another issue. :)

**Comment by razielgn** [comment]
No I meant, what if there's an attribute named `edit` in a sql row / mongodb document?

**Comment by nashby** [comment]
Actually, 21dfbf7 commit doesn't resolve the problem with yamlizing `id` attribute in ActiveRecord because AR has `id` and not `_id` like Mongoid has (https://github.com/codebrawl/arnold/commit/21dfbf71a6a5bc2760b25ee6758062645046d892#L0R46). Tests for AR are passing because we have no `id` attribute in our AR model at all. It's only `name` we have.
Should I fix it or @levicole will make it?

**Comment by levicole** [comment]
Doh! I will fix it this evening.

**Comment by nashby** [comment]
awesome, thanks!

**Comment by jeffkreeftmeijer** [comment]
Didn't Github have some kind of feature which would pull in comments from the pull request's commits and show them here? Anyway, I placed some comments: https://github.com/codebrawl/arnold/commit/21dfbf71a6a5bc2760b25ee6758062645046d892#comments :)
