### ISSUE TITLE
Arnold#edit turns to nil attributes not involved

### ISSUE THREAD

**Issue by razielgn** [codebrawl/arnold#8]
See https://gist.github.com/1151526
If edit is called without the attributes wanted id is turned to nil, otherwise it turns to nil those not involved in the editing.
This behavior doesn't appear in the tests, where I forced a `should_not be_nil` check after `edit`.

**Comment by jeffkreeftmeijer** [comment]
Opening since this doesn't have any tests. I'm working on a patch right now.
